# Generated by Django 2.2.2 on 2019-06-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_notifications', '0002_auto_20171003_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticetype',
            name='description',
            field=models.CharField(max_length=500, verbose_name='description'),
        ),
    ]
